/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tm;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import tm.model.MainModel;
import tm.presenter.MainPresenter;
import tm.view.MainView;

public class App extends Application {

    public static void main(String[] args) throws Exception {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        MainView mainView = new MainView();
        MainModel testModel = new MainModel();
        Scene scene = new Scene(mainView);
        new MainPresenter(mainView, testModel);

        primaryStage.setTitle("Na sowas, Quadratwurzeln!");
        
        primaryStage.getIcons().add(new Image(getClass().getResourceAsStream("/images/Logo.png")));
        primaryStage.setResizable(false);
        primaryStage.setScene(scene);
        primaryStage.setWidth(376);
        primaryStage.setHeight(480);
        
        primaryStage.show();
    }

}
