/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tm;

import javafx.application.Application;
import javafx.stage.Stage;

import tm.presenter.MainPresenter;


/**
 * TODO empty this
 */
public class App extends Application {

    public static void main(String[] args) throws Exception {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        MainPresenter mainPresenter = new MainPresenter();
        mainPresenter.initialise(primaryStage);
    }

}
